### ISSUE TITLE
World only generates surrounding chunks

### ISSUE THREAD

**Issue by TuboWorm** [orangeadam3/terra121#108]
So i have followed tutorials and it seems everything should be ok however when i load up the world it seems to only generate the few chunks around where i spawn. The rest is all just very deep water.

**Comment by taeko-chan** [comment]
that's "null island". you'll need to use the /tpll <lat><lon> command to teleport somewhere meaningful.

**Comment by TuboWorm** [comment]
I just get teleported to water still

**Comment by taeko-chan** [comment]
try one of these locations:
https://github.com/orangeadam3/terra121/blob/master/COOL_LOCATIONS.md

**Comment by TuboWorm** [comment]
I honestly feel so stupid. It worked. How do i find where my town is? how do i convert the coordinates from real life to minecraft. Sorry I am clearly too old for this!

**Comment by taeko-chan** [comment]
no problem, can be a bit confusing :)
go to google maps and click somewhere in your town on the map. at the bottom, there should be a windows that pops up, with the town name in bold on top and below there should be the coordinates. click on them, and then you should be able to copy them from where you would normally search for something. then just paste them after /tpll with a space afterwards. be sure you get the one without degrees, so something like: 47.345596, 8.550502

**Comment by ILikeTrains27** [comment]
and remember to remove the comma

**Comment by taeko-chan** [comment]
There was a recent commit that added the ability to leave the comma in, but it’s worth checking because you may have an older version (idk if there’s an official build with that new a commit)
