### ISSUE TITLE
[Question] Railway Generation

### ISSUE THREAD

**Issue by ChengChu1444** [orangeadam3/terra121#11]
Hi, 
is there are reason why railways are not generated with the roads? Would be cool if they were also generated. Thanks for developing this mod.

**Comment by orangeadam3** [comment]
Yeah, I'm just not sure how to automatically place rails nicely. It's probably possible I just haven't gotten around to it.

**Comment by ChengChu1444** [comment]
Ah okay. Thanks for the response though
