### ISSUE TITLE
Roads and outlines not working

### ISSUE THREAD

**Issue by WAWEQRWQEWQEWE** [orangeadam3/terra121#113]
So i have had a problem with the roads. No roads are showing up. I am not sure if there is something wrong with my settings, if i downloaded it wrong, or if the roads don't work on mac.
I have roads and outlines on but i a am not sure if any other setting messes it up. i have the lastes version.

**Comment by z3nth10n** [comment]
Do you have Letsencryptcraft mod installed?

**Comment by WAWEQRWQEWQEWE** [comment]
No. what version do i need

**Comment by WAWEQRWQEWQEWE** [comment]
is it the 1.12.2 one?

**Comment by WAWEQRWQEWQEWE** [comment]
i downloaded the mod and it is still not working.

**Comment by taeko-chan** [comment]
You shouldn’t need letsencryptcraft. Try the roads not spawning section in this guide. https://github.com/orangeadam3/terra121/blob/master/TROUBLESHOOT.md

**Comment by WAWEQRWQEWQEWE** [comment]
i am not too sure what this means. i had done everything but i don't know what to do in the java file.

![Screen Shot 2020-04-16 at 2 37 39 PM 2](https://user-images.githubusercontent.com/63811815/79501653-04f2f300-7ff4-11ea-9ff5-28dd14b1505a.png)

**Comment by taeko-chan** [comment]
in finder press shift+command+g and a window should pop up that says go to. after you paste the path into the text box, press enter to go to the folder

**Comment by WAWEQRWQEWQEWE** [comment]
i am there but i don't know what to do after. so do i just launch the game?

**Comment by taeko-chan** [comment]
yeah, and make a new terra 121 world

**Comment by WAWEQRWQEWQEWE** [comment]
k

**Comment by taeko-chan** [comment]
if that doesn't work, a simpler way (and what i did to get it to work in the beginning) is to just put "-Djavax.net.ssl.trustStore=<JVMwithoutBin>/lib/security/cacerts" (assuming you're on a mac) at the end of the jvm args as described at the bottom of the same link

**Comment by orangeadam3** [comment]
Usually, these problems are caused by having other mods installed than just the 3 required ones. Do you have any other mods installed? Also send your runtime log.

**Comment by orangeadam3** [comment]
Also for future reference, LetsEncryptCraft is no longer a requirement as of 0.1.4. because the code for LetsEncryptCraft is built in.

**Comment by WAWEQRWQEWQEWE** [comment]
Thank you guys for the help it works. I hope you will have a great day.
