### ISSUE TITLE
 issue when building gradlew.bat

### ISSUE THREAD

**Issue by labrass** [orangeadam3/terra121#125]
Hi!
forge-1.15.2-31.1.74 installation is ok

But I'm stuck width this issue when building gradlew.bat
"Plugin [id: 'io.github.opencubicchunks.gradle.fg2fixed'] was not found in any of the following sources"
I've tried the troubleshooting tips but it still the same error in the first step...
I've the last version of java (build 1.8.0_251-b08) and windows 10 1909
 I'am very beginner in minecraft mods installation, so... thank for your help :)

labrass

**Comment by orangeadam3** [comment]
You dont need to compile. You can get it from curseforge or if you want the latest snapshot (possibly unstable) you can download from https://jenkins.altillimity.com/job/Terra/

**Comment by labrass** [comment]
ok, I finally succeeded install it, thanks :)
