### ISSUE TITLE
Nevada generating the wrong terrain

### ISSUE THREAD

**Issue by LittlePippy** [orangeadam3/terra121#13]
when you go anywhere in nevada its a flat grass plain which if you seen Nevada outside of vegas its not the case at all. id like to see nevada fixed in the future!

**Comment by orangeadam3** [comment]
The biome classification is based on soil type and climate but I'm not an expert in that sort of thing so the classification isn't great right now, I'd be open to anyone helping match soil suborder and climate to biomes.

**Comment by LittlePippy** [comment]
Nevada seems to be subject to just being grass in minecraft. Iy seems yo be whatevers going on with data these real world mods are using. the only time in general nevada was ever not a flat or blocky grassland was Outerra....
