### ISSUE TITLE
No build folder at C:/users/~/Documents/terra121/build

### ISSUE THREAD

**Issue by OutlanderForge** [orangeadam3/terra121#133]
When I build the mod, it says that it succesfully built but it doesn't make a build folder. Also, can I just put the client terra121 mod into my server mod folder?

**Comment by orangeadam3** [comment]
You dont need to build the mod. You can get the latest version from the release tab/curseforge, or if you want to work with bte you can use their modpack or download the jenkins snapshot. jenkins.altillimity.com/job/Terra/

You should only be building if you want to mess with the source code of the mod.

**Comment by OutlanderForge** [comment]
Oh Ok thanks, that helped me a lot.
