### ISSUE TITLE
Airocean::toGeo and Minecraft's origine on the null Island

### ISSUE THREAD

**Issue by SmylerMC** [orangeadam3/terra121#136]
This is more a suggestion than a real issue:
I understand that all points on the Minecraft world generated with the airocean projection cannot be mapped to a point on earth, which is why toGeo returns OUT_OF_BOUNDS, but there is one special case which seems strange: toGeo(0.0, 0.0) returns OUT_OF_BOUNDS despite the fact that it corresponds to 0°/0° on the null island, so could it be possible to add a special case for it?
Other projections might be affected, I haven't checked.
I will add a check to my own code (https://github.com/SmylerMC/terramap), but I figured it could be included directly into Terra1:1 .

**Comment by orangeadam3** [comment]
Its sort of to be expected. Null island on the bte projection is the intersection of the two regions of the map, one it the western-ish hemisphere and one in the eastern-ish hemisphere. I guess technically it would coorospond with a point (not 0,0 something else nearby, I can't remember) but it's such a minor issue that the slowdown for having a special case would probably not even be worth it. Also updating the projection would be a pain cause we now have 2 or 3 versions in other languages that would have to be updated.

**Comment by SmylerMC** [comment]
Ok, I admit it's really a rare edge case, thank you for your response.
I'm closing the issue.
