### ISSUE TITLE
No roads

### ISSUE THREAD

**Issue by Petrosado** [orangeadam3/terra121#154]
No roads are spawning for me and neither is building outline things any way i can fix this?

**Comment by orangeadam3** [comment]
Make sure they are both enabled in the customize world settings. If you still have issues, check for any errors in your log or just link your log on pastebin.

**Comment by Petrosado** [comment]
[latest.log](https://github.com/orangeadam3/terra121/files/5275985/latest.log)
This is the log no idea whats wrong
