### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by adas12w** [orangeadam3/terra121#155]
Have you ever thought about Minecraft geography; it's boringness, emptyness ans repetition. Maybe you can add real world geography to Minecraft. I know it's a hard thing but it'll give more depth

**Comment by shejan0** [comment]
That is what this mod does.

This is gone into more detail in the (Readme)[README.md] file, but to summarize, this mod pulls information about the earth's surface from different datasets on the internet, such as terrain (geography, heightmaps, biome, etc.) and man-made paths (like roads, walkways, etc.), then start a Minecraft World generation with CubicWorldGen (the world generator for Cubic Chunks) with that information.

So if you do use the mod you would then have real-world geography in Minecraft.
