### ISSUE TITLE
Support Offline Mode

### ISSUE THREAD

**Issue by callowaysutton** [orangeadam3/terra121#16]
I was wondering if some type of offline mode could be made which just had a big tarball of all the data needed to generate the map.

I'm just curious if this is possible because I would rather download one huge data pack from these API providers than constantly hitting them with traffic if I made a server. Also, I'm sure the guys running these services would appreciate it as well

**Comment by orangeadam3** [comment]
Unfortunately, this is not really practical unless the resolution was reduced. The planet OSM data when compressed is 49GB, the terrain data has roughly arcsecond resolution which puts it roughly in the neighbor hood of a TB not to mention the tree data. If someone actually went through the trouble of downloading it all, I might feel inclined to write an additon for that sort of thing.

**Comment by orangeadam3** [comment]
I have been thinking of getting my own overpass server or making a custom algorithm for OSM stuff because the default OpenStreetMap Overpass server is run by a small German company while the rest are large organizations.
