### ISSUE TITLE
Generation of Specific Areas of the world?

### ISSUE THREAD

**Issue by MrAppu** [orangeadam3/terra121#168]
If you did not understand the title, basically I am saying that can we make ,for example, A country without other landmass like surrounding countries, a standalone map, taking a specific piece of land. We can choose which areas in the world we want to generate to play.

**Comment by orangeadam3** [comment]
I think there are mods for generating small areas. I want to say the Build the Earth team had to do stuff like this so you could start by looking there. However, the maps can get very large very fast and unless you are doing a very small country, the could end up being too large to handle.

**Comment by MrAppu** [comment]
Thanks mate, I will check them
