### ISSUE TITLE
water for servers!

### ISSUE THREAD

**Issue by Mapagmataas** [orangeadam3/terra121#174]
Hi there, on my server world there are no oceans, and some rivers, i think that water fix wiil solve it but i dont no what level type is it or how to apply it on server, pls help
btw sor for my english, im not amerikanec

**Comment by orangeadam3** [comment]
Create a single player world with the settings you want and type the command:
/terra world
Copy the JSON ouput and use it as "generator-settings" in your server's properties

**Comment by Mapagmataas** [comment]
Thank u!

**Comment by orangeadam3** [comment]
Also refer to https://github.com/orangeadam3/terra121/blob/master/USING_SERVER.md
For other details
Level type is EarthCubic
