### ISSUE TITLE
Issues running server sided

### ISSUE THREAD

**Issue by daddyparodz** [orangeadam3/terra121#24]
I'm trying to host a Minecraft server for this mod, but I'm encountering some issues.
What's the level-type to set into server.properties for this mod?
Works perfectly on singleplayer, but run from a server it doesn't even output logs into the console...
I tried:
level-type=planet_earth
level-type=earth
level-type=planet

**Comment by orangeadam3** [comment]
I belive it is "EarthCubic"
planet earth is just an english localization

**Comment by daddyparodz** [comment]
Thank you it worked perfectly! :)
