### ISSUE TITLE
SpongeForge !!

### ISSUE THREAD

**Issue by muntder123** [orangeadam3/terra121#26]
so iam trying to use Mods / Plugins in my earth world server
my mod list is :
1- CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar
2- CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar
3- effortlessbuilding-1.12.2-2.16.jar
4-letsencryptcraft-1.10.2-1.2.0.jar
5- malisiscore-1.12.2-6.5.1.jar
6- worldedit-forge-mc1.12.2-6.1.10-cc975.01-SNAPSHOT-dist.jar
7- terra121-0.1.3.jar 
so i tried to add SpongeForge its this : https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2
---
and this happend : https://hastebin.com/qoyanicili.md
any idea how to fix or add complitable?
or maybe support this !
https://github.com/KettleFoundation/Kettle 

what iam trying to do is add plugins support to my earth server !! 
help please or add support to SpongeForge or Kettle !

**Comment by orangeadam3** [comment]
Im not sure. I think sponge has to do with cubic chunks and it looks like you have two versions of that, so mabye delete that cc SNAPSHOT thing. If your working with the build the world project try to ask in the discord first if minecraft wont start

**Comment by Barteks2x** [comment]
Cubic chunks is not compatible with sponge forge and won't be compatible in the near future.
