### ISSUE TITLE
Can someone please help me with coordinates?

### ISSUE THREAD

**Issue by Leebondoop** [orangeadam3/terra121#27]
I keep trying to go to Rainier, WA but the coordinates I have (46.73944444, 121.91833333) don't work, it just keeps telling me that all the clients need to be numbers or something like that

**Comment by taeko-chan** [comment]
Try it without the , in between

**Comment by orangeadam3** [comment]
Also West/South Correspond to negative numbers so 46.73944444 -121.91833333 is in Washington wheras 46.73944444, 121.91833333 is in easten China. Be careful with that. Use "/tpll 46.73944444 -121.91833333" without quotes
