### ISSUE TITLE
Real life north is In game east

### ISSUE THREAD

**Issue by RandomMangaFan** [orangeadam3/terra121#29]
It appears that the world generates in the wrong direction. When I look at the terrain and use the F3 screen to see which way is north, I find that the actual, real-life north is the ingame Minecraft east. 

Is this an intentional feature because of technical limitations, or is this a bug?

**Comment by taeko-chan** [comment]
according to @orangeadam3, it was for purposes of backwards compatibility. if you go into the customize tab when you generate the world, you can change "orientation" to upright.

**Comment by steadyaero** [comment]
How do you change this on a dedicated server?

**Comment by MoKe12g** [comment]
Generate a world whit this orientation on your client and upload it to your server.
The Server will keep the orientation which was set by the client.

**Comment by steadyaero** [comment]
I guess that works as a bandaid, but that seems like something that should be read from the server.properties file.
