### ISSUE TITLE
OSM type:multipolygon buildings do not generate

### ISSUE THREAD

**Issue by Gyrogaming01** [orangeadam3/terra121#30]
Basically title, buildings with type 'multipolygon' on OSM don't seem to generate in game, noticed when one of my college buildings didn't appear 😢. Checked a few others with multipolygon shape and none generated.

**Comment by orangeadam3** [comment]
Yeah, I had hoped multipoly buildings with no labels on the ways were rare enough to avoid implementing. It just sounds like a pain in the ... But if you notice it much, I guess i can work towards it in the next version.

**Comment by orangeadam3** [comment]
If you wouldn't mind, could you send me the location of your college building that doesn't show up, so I can test it? I am addressing the bug right now.

**Comment by orangeadam3** [comment]
Fixed. I think...
