### ISSUE TITLE
Terra121 doesn't fire all generation events and CC API generator registry

### ISSUE THREAD

**Issue by Barteks2x** [orangeadam3/terra121#33]
The following are not done
```
           MinecraftForge.EVENT_BUS.post(new PopulateCubeEvent.Pre(world, rand, pos.getX(), pos.getY(), pos.getZ(), false));
           // populator code
           MinecraftForge.EVENT_BUS.post(new PopulateCubeEvent.Post(world, rand, pos.getX(), pos.getY(), pos.getZ(), false));
            CubeGeneratorsRegistry.generateWorld(world, rand, pos, cubicBiome.getBiome()); }
```

**Comment by orangeadam3** [comment]
I can do the bus events but can you explain what CubeGeneratorsRegistry.generateWorld is for?

**Comment by orangeadam3** [comment]
Also I noticed you keep getting a lot of the same question about installing cc/cwg on curseforge, should we add some docs here about not using the download button.

**Comment by Barteks2x** [comment]
`CubeGeneratorsRegistry.generateWorld` generates things from mods registered as a cubic populator (equivalent to forge's IWorldGenerator).

As for info about downloading - I created a FAQ section in CC, but it may be useful to add it somewhere to terra121 too.

**Comment by orangeadam3** [comment]
Oh ok that possibly explains a custom ore bug people were having earlier. Ill try to push tonight (aka like 5 hours) then
