### ISSUE TITLE
Suggestion: buildings actually shaped as such...

### ISSUE THREAD

**Issue by LittlePippy** [orangeadam3/terra121#43]
Honestly i should make it a question but i have no idea where so ill make it an issue. Is there any plans to make the outlines actual buildings and could there possibly be building types? such as making houses typical villager homes, skyscrapers, fast food restaraunt tagged buildings being a generic restaraunt, and convinent stores somehow being unique? (Maybe mcdonalds can be actual mcdonalds structures lol)

I assume this is implementable (but possibly not easy) because geobloxer and OSM 3d buildings as well as being able to import those as OBJ with a program.

**Comment by orangeadam3** [comment]
This is not planned at the moment. The more servers added the slower everything gets and the more points of failure there are. There is the build the earth project which seeks to build many buildings even some generic ones.

**Comment by LittlePippy** [comment]
Feature has been added thanks to @AidenLoveLace I will close this now.
