### ISSUE TITLE
'Cancel' and 'Done' buttons not translateable

### ISSUE THREAD

**Issue by Blueberryy** [orangeadam3/terra121#45]
Add them to language files please :P

**Comment by orangeadam3** [comment]
Yeah, oversight on my part. Neither are the command outputs, I'll try to add them today.

**Comment by orangeadam3** [comment]
Are you going to make a pull request for another language? If so, please do. I'm excited for this kind of help that I can't do myself. However, only if you are very familiar with the language, please avoid using automated translation like google translate.

**Comment by Blueberryy** [comment]
Yes. But i'll make it when update for language files come.

**Comment by orangeadam3** [comment]
Ok, ill try and get it today.

**Comment by orangeadam3** [comment]
I found out Minecraft already has localizations for those words so I used those the same way yes and no work. I also updated the commands to use localizations.
