### ISSUE TITLE
Advanced Water No Mod Supporting

### ISSUE THREAD

**Issue by SuperTemplar** [orangeadam3/terra121#48]
I noticed that mods randomly remove water from spawning at all while using Advanced water. Which is almost needed to use the map gen in survival near natural water levels, since without it, it is nothing but water under level 0. Mods most prone (almost exclusively) to doing this are mods that have items that are placeable as blocks. This isn't a complaint but more of something to take note of. Not sure how placeable objects affect world gen, but water yeets itself with those mods particularly, almost exclusively. Just avoid those is my advice.

EDIT: Mods: Fire and Ice (it's library file also triggers eternal drought), Galacticraft, and Placeable Items.

**Comment by orangeadam3** [comment]
Can you give some more concrete examples of mods that cause issues and exactly what problems they cause?

**Comment by SuperTemplar** [comment]
Water source blocks don't generate during world gen.

**Comment by orangeadam3** [comment]
Which mods cause this?

**Comment by SuperTemplar** [comment]
"EDIT: Mods: Fire and Ice (it's library file also triggers eternal drought), Galacticraft, and Placeable Items." At least these. Not sure if more.

**Comment by SuperTemplar** [comment]
https://imgur.com/IOP23uM

**Comment by orangeadam3** [comment]
Likely interfering with letsencryptcraft. Send a pastebin of your log while running one of them

**Comment by SuperTemplar** [comment]
https://pastebin.com/nnch4Zt2
This type of log?

**Comment by orangeadam3** [comment]
Yep. "An error occurred whilst adding the Let's Encrypt root certificate. I'm afraid you wont be able to access resources with a Let's Encrypt certificate D:" 

That's the problem. Looks like the mods interfere with adding certs which prevents roads . The same bug was reported for a different mod. (#21 )
Not sure why that doesn't work. It could be that the mods are incompatible with letsencryptcraft or something with my implementation.

**Comment by orangeadam3** [comment]
If you really need to play the mod, you could try one of the old certificate solutions like changing your JVM in TROUBLESHOOT.MD to get the certificate back.

**Comment by SuperTemplar** [comment]
I am not sure exactly what you mean by changing my JVM but I am sure I can find some resources online that will help guide me through the process. I don't need to, but it would be nice, especially since there are a large amount of other mods that might have the same issue. I'll test it and find out if it solves it.

**Comment by SuperTemplar** [comment]
From my minimal testing, changing JVM does indeed seem to fix the issue.
