### ISSUE TITLE
(Russia, Krasnoyarsk) Wrong Terrain Generation

### ISSUE THREAD

**Issue by rastamangames** [orangeadam3/terra121#56]
This is another example of bad terrain generation.

Here a screenshot taken from Google.Maps. You can see marked big roads as well.
[Google.Maps Screenshot](https://i.imgur.com/02IlnOu.png)
You can see a bridge over "Yenisei" river. This is a big river in real life.

And here what i got in the game:
[Minecraft Overview](https://i.imgur.com/EwdSGCu.png)
There is no "Yenisei" river. Only field of grass.
This river not only long and wide, but deep as well...

**Comment by orangeadam3** [comment]
Make sure you enable advanced water in the customize world settings if you want to see inland bodies of water.
