### ISSUE TITLE
Roads don't seem to be generating

### ISSUE THREAD

**Issue by tyler137313** [orangeadam3/terra121#6]
In version 0.1.3, roads don't seem to be appearing anywhere I go. I went to the center of New York City (lat: 40.634799, long: -73.969231) and didn't see anything there. I also checked the same location used in your Yavapai Point screenshot, as there appears to be a small road on the left, but didn't see anything there on my world. This is also after I checked to make sure Generate Structures was on and the Planet Earth's Spawn Roads option was on too. Am I missing anything or is there a bug preventing the world from generating them?

**Comment by shejan0** [comment]
Please enable the log from your launcher, most likely it is regarding the certificates that Overpass utilizes.

We have instructions to fix that in [our troubleshoot documentation](TROUBLESHOOT.md)

**Comment by tyler137313** [comment]
Thanks for the quick reply. It was a certification issue with the roads. I followed the instructions in your troubleshooting document for finding and then switching JVM through the Minecraft launcher and that worked like a charm.
