### ISSUE TITLE
[Feature Request] Add Dymaxion and/or DymaxionEdited map projections

### ISSUE THREAD

**Issue by redbrain1014** [orangeadam3/terra121#72]
In PippenFTS’s new Build the Earth video, he talks about using an edited version of the Dymaxion map projection to maintain balance between landmass shape and relation. Would you consider implementing this in Terra121?

**Comment by orangeadam3** [comment]
Yeah that would be the idea, the mod has to support it for the projection to work. I'm working on it right now.

**Comment by redbrain1014** [comment]
Great, thanks!

**Comment by James103** [comment]
Note: Dymaxion-Edited in its current form would cut off Iceland (which is actually one contiguous island). Will Iceland be pieced back together in the final implementation of Dymaxion-Edited?

**Comment by redbrain1014** [comment]
The folks on the BTE Discord have coded "Airocean" (their version of Dymaxion-Edited) and it seems to be going very well. Thus I am closing this request.
