### ISSUE TITLE
[Suggestion] Universal Transverse Mercator Projection

### ISSUE THREAD

**Issue by LexSong** [orangeadam3/terra121#77]
[Wikipedia: Universal Transverse Mercator](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system)

The UTM system divides the Earth into 60 zones, each 6° of longitude in width.
The amount of distortion is held below 1 part in 1,000 inside each zone.

I wrote a script to demonstrate what it looks like if we put all the zones together into one single map:
![world](https://user-images.githubusercontent.com/35987111/78466172-bbbbbd00-7730-11ea-9304-c76430b20347.jpg)

Each zone is 668,224m east to west, 20,000km south to north, or 41,764 by 1,250,000 chunks in Minecraft. I think it's an interesting alternative way to map the whole world while keeping the distortion minimal. The boundaries between the zones will be an issue. However, we should be able to config what zone each chunk should belong to, and to put boundaries into oceans or deserts, for example.

**Comment by orangeadam3** [comment]
Any projection needs to be a bijective mapping (not having duplicate locations) and in terms of overall distortion, this seems fairly similar to equirectangular. Look at the size of Antarctica. There is always distortion, some maps are just better at hiding it.

**Comment by LexSong** [comment]
Locally distortion should be minimal. Just look at the size of Iceland, British Isles, and Svalbard. Globally the map would look like equirectangular projection. However, we duplicate high latitude regions instead of distorting them.

We could avoid duplication and just filling the gaps with oceans, but I would argue it may actually look worse:
![Image](https://upload.wikimedia.org/wikipedia/commons/9/9b/Transverse_Mercator_meridian_stripes_20deg.jpg)

I don't see bijective mapping is an issue here. Each zone should be a bijective mapping and we could easily determine the zone number by checking the longitude.

**Comment by orangeadam3** [comment]
It does need to be bijective because a reverse function is also required. You are welcome to fork and try to implement the version with oceans filling the gaps. Projections are just child-classes of GeographicProjection (I could give you more details if you are interested). I can't promise bte would adopt it but I would be happy to add it as an option to my mod.

**Comment by LexSong** [comment]
Done. #82
