### ISSUE TITLE
[Suggestion] A second level of the Nether for faster travel over very large distances

### ISSUE THREAD

**Issue by James103** [orangeadam3/terra121#84]
I think that a second Nether layer will be required because of the extreme distances and resource spread involved with putting Earth into Minecraft at a 1:1 scale and playing survival mode, combined with the inaccuracy caused by increasing the scale factor making short-distance (<10km) travel via the Nether inviable.

This new layer would be an entirely separate dimension (hereafter referred to as "Hot Nether") to the base Nether that we already have. The scale factor would be much bigger compared to the normal Nether, with every block you travel in the Hot Nether being equal to 1,000 blocks (1 km) in the Overworld, compared to the 8:1 scale factor for the regular Nether. You should be able to access the Hot Nether by building a Nether Portal and lighting it with a Nether Star. This creates red portal blocks and does not consume said Nether Star. Returning back just requires a flint and steel to (re)light the return portal and returns you to the Overworld.

### Optional implementation 
Any entities (including players) in the Hot Nether will take damage if they do not have either the Fire Resistance effect or 5 levels of Fire Protection on their armor. This fire damage will kill unprotected players in minutes. Blocks like ice and snow will melt (disappear) regardless of light level, no crops will grow at all, and fire will spread faster. Iron would be about as common as nether quartz here, due to its abundance in the Earth's core.

In the config files, it should be possible to change the scale factor between the Overworld and regular Nether, and it should be possible to change the scale factor between the Overworld and Hot Nether. Both values are in Overworld blocks per Nether block.

**Comment by MoKe12g** [comment]
Theoretical you can expand this concept also for the vertical coordinates. To get much higher in the overworld.

**Comment by James103** [comment]
Due to the elevations involved, the regular Nether could have some vertical compression, at 1 vertical Nether block equals 8 vertical Overworld blocks. The Hot Nether could have even more vertical compression, at 1 vertical Hot Nether block equals 64 vertical Overworld blocks.

If #85 is implemented, then a new layer of the Nether, hereafter referred to as the Superhot Nether, may need to be added to access the deeper layers of the Earth. It would be just like the Hot Nether, except that entities take 1 HP of fire damage per second instead of every few seconds, you need 10 levels of Fire Protection on your armor to prevent this fire damage, fire spreads near-instantly, and the scaling of 1 Superhot Nether block to 1,000 Overworld blocks now applies vertically. The way to access the Superhot Nether remains similar to that for the Hot Nether, except you need a beacon instead of a nether star to light the portal, which produces orange portal blocks.

In the config files, it should be possible to change both the horizontal scaling and vertical scaling for all 3 Nether layers (Normal, Hot, Superhot), as well as the items required to light the Hot Nether and Superhot Nether portals and whether they are consumed.

**Comment by orangeadam3** [comment]
So I've had a variation on this planned for a while in my "future plans" section. I did some research and changing the scale factor to 1:1k should be possible (with some tweaks to the linking system). I'm not sure about the second nether. I don't know if new dimentions can be added while still making the mod server side only.

**Comment by orangeadam3** [comment]
I cannot add blocks while maintaining server side only status. I could mabye reuse assets like an endportal (since they don't work in the nether anyways) to help with this but I'm not sure. Mabye there could just be periodic pre built end portals in the nether to take you to the supernether and you can exit the super nether from anywhere by using an item like a nether star.

**Comment by MoKe12g** [comment]
We should stay modular and develop a sub-mod to implement the hot nether and maybe some new items. Because I think it doesn't really belong in the main Terra121 mod. It also will slow down the mod development if we dont develop both mods independly.

**Comment by orangeadam3** [comment]
Yeah if anyone wants to start just keep in mind that it should not introduce new blocks.

**Comment by MoKe12g** [comment]
I'm also not sure it we should implement faster nether traveling in this mod.
It would break server in ways that no one can predict. No one will think that the nether traveling feature is from terra 121 and not from another mod.

**Comment by Barteks2x** [comment]
> So I've had a variation on this planned for a while in my "future plans" section. I did some research and changing the scale factor to 1:1k should be possible (with some tweaks to the linking system). I'm not sure about the second nether. I don't know if new dimentions can be added while still making the mod server side only.

You can't actually make the scale 1:1k, because MC is searching for portals only in 256x256(x256) area range. This would mean that with just a single block of difference in the **player** position in the nether side would mean that the overworld portal is completely missed.

And portal linking data is, as far as I remember, not serialized. It's just a cache.

You could plausibly increase the scan radius to 512x512 without too much of a slowdown but anything beyond that would likely be too much, or you would need a modified portal design that you can scan for very efficiently.

Server-only dimensions can be added, but I'm not sure if forge has an API for it. So it may require a coremod.

**Comment by James103** [comment]
The superfast Nether travel may not be necessary if the following alternate suggestion is implemented either in a separate mod and/or in this mod:

By standing on a beacon and having the required consumables/items, you can use the `/tp` and `/tpll` commands in survival mode. In order to actually teleport this way in survival mode, you would need to run the same command twice within 30 seconds for confirmation. The first execution calculates how much it would cost to teleport there, how long it will take, and how far away the destination is, while the second execution actually checks for and deducts the consumables to complete the teleportation, including simulating the time required to teleport.

In the config files, you should be able to set for each beacon tier, the max range of the teleport (in blocks) as well as what resources are consumed and how much. The required resources can be one or more of the following:
* HP (health points) - be careful, this can hardcap your teleport range!
* XP (experience) - draws from player XP
* Food points - includes any food in your inventory
* Time/Speed - defines how long the teleport takes, defaults to real lightspeed (299792458 m/s). Note: The time required to teleport is fully simulated, meaning that crops will grow, furnaces and entities will process, etc.
* Items - specify what items and how much of each item
* Fluids - specify what fluids and how much of each fluid
* Energy* (RF/FE/EU) - ignored if no energy mod present, draws from your energy storage items
* EMC* - ignored if ProjectE isn't present, draws from player EMC as well as stored EMC
* Custom command - if the command succeeds, the teleport proceeds. Else the teleport stops.

**Comment by Barteks2x** [comment]
Another possibility would be to reuse the end dimension for very fast travel and add another x8 or even make it x16 distance factor there. This would require adding a possibility of making a special end portal but that should be doable as server only.

**Comment by orangeadam3** [comment]
I was thinking of increasing the range to 1024x1024 but assuming a portal was 3x1x2, you could only look at roughly 1/6th of the blocks (maybe less if you factor the obsidian frame) to help offset the slowdown, but I like ethier the end or super nether ideas better.

**Comment by Barteks2x** [comment]
And the large issue is not loading blocks, but loading chunks.

**Comment by James103** [comment]
Closing, as the mod appears to no longer be maintained and the feature would not fit.
