### ISSUE TITLE
[correction] spelling

### ISSUE THREAD

**Issue by cryptearth** [orangeadam3/terra121#87]
> REQUIRED: Minecraft Forge for the corrective version of Minecraft of the mod (currently Minecraft 1.12.2, this mod is tested using 2847 and 2768)

aside from those extreme old versions of Forge (you could had at least used something more recent like the 28xx from 2019) how the F someone came up with that line - with that word "corrective" in particular - where you from that presumably G translator came up with "corrective"?
please look up its meaning on something like https://www.oxfordlearnersdictionaries.com/definition/english/corrective_1
what you meant to write should be some line like this:

> REQUIRED: Minecraft Forge (tested with 2847 and 2768)

FIN - that's it - from the build number itself it comes clear that this is for MC 1.12.2 ... same goes for the other lines of that type

**Comment by orangeadam3** [comment]
Ha. Yeah, @shejan0  tends to do stuff like that. Not sure why, English is his first language.

**Comment by cryptearth** [comment]
well - but he's not Ringo who came up with things like A Hard Day's Night
and mis-using "corrective" in that line doesn't even make sense as its meaning comes closer to "fix an issue" rather than "using the right tool (for the job)"
sry - was interested in about helping with this build the world in mc - but its founder didn't posted any info about the used mods (instead only linked to discord) and reading this here makes me think: "ok, mc is 10years now - and some kiddo reinvented the wheel like noone else already had this idea"
