### ISSUE TITLE
Wrong Biome

### ISSUE THREAD

**Issue by katykat5099** [orangeadam3/terra121#91]
The biome in a town called Redditt, ON, Canada is generated as a desert biome. In real life it is a Boreal Forest, so it should be taiga.

**Comment by taeko-chan** [comment]
this is a known issue - lots of places have this problem. it has to do with classification of the real world data into minecraft biomes. a fix is planned for version 0.1.5 as stated in the milestones section: https://github.com/orangeadam3/terra121/milestone/1

**Comment by katykat5099** [comment]
Oh, I should have looked further than. Thanks so much for letting me know, though!
