### ISSUE TITLE
No Land 

### ISSUE THREAD

**Issue by sofaslapper** [orangeadam3/terra121#97]
I might be doing something wrong, but when I opened up the world for the first time I tried teleporting to Long Island and all I found was an ocean. Then I tried a random place in New Mexico and all I found was an ocean. Then I teleported to the center of the United States and... ocean. But one time when typing in the coordinates to the center of the US, I forgot the “-“ before the last coordinate and I got teleported to a jungle. So clearly there is land, but I can’t seem to be able to find it.

**Comment by orangeadam3** [comment]
Use /tpll latitude longitude
