### ISSUE TITLE
Consistent crashes around overhanging terrain

### ISSUE THREAD

**Issue by TrueCP6** [orangeadam3/terra121#98]
If you teleport your self to the base of El Capitan (`/tpll 37.728197 -119.637187`) and fly up about 600 blocks the game crashes every time.

**Comment by James103** [comment]
Do you have the crash logs (`crash-<DATE>_<TIME>-<TYPE>.txt` located in `.minecraft\crash-reports`)?

**Comment by TrueCP6** [comment]
Here: [crash-2020-04-11_20.57.20-server.txt](https://github.com/orangeadam3/terra121/files/4465219/crash-2020-04-11_20.57.20-server.txt)

**Comment by James103** [comment]
Have you tried increasing the stack size to at least 4 MB (`-Xss4m`)? What did you get?

**Comment by orangeadam3** [comment]
Try also turning on three_water in the mod config. It helps reign in some of minecraft's rediculous water physics.

**Comment by TrueCP6** [comment]
I applied both of the fixes and tried twice. The first time it resulted in chunks not loading and a crash and the second time it worked fine. The dataset seems to not include the overhang as it is not present in game so this is most likely an unrelated problem. Closing for this reason.
